version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=test_database
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  spring:
    container_name: spring-container
    build: ./create-web-service  # Specify the directory of the Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
    depends_on:
      - db
    restart: always

  react:
    container_name: react-container
    build: ./react-app  # Specify the directory of the Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - spring
