version: "3"
services:
  db:
    image: "postgres"
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=test_database
    ports:
      - "5432:5432"
    volumes:
      - ./Database/test_database.sql:/docker-entrypoint-initdb.d/test_database.sql
      - ./db-data:/var/lib/postgresql/data
    restart: always

  spring:
    container_name: spring-container
    build: ./create-web-service  # Specify the directory of the Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - db

  react:
    container_name: react-container
    build: ./react-app  # Specify the directory of the Dockerfile
    ports:
      - "3000:3000"
    command: >
      bash -c "npm start"
    depends_on:
      - spring
